name: "Test, Build, and Distribute iOS App"

on:
  workflow_dispatch:
    branches: "*"

jobs:
  test_build_and_sign:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -scheme "IBHGithubAction" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -resultBundlePath $RUNNER_TEMP/test-results \
          -timeout 400

      - name: Convert test results to HTML
        run: |
          mkdir -p $RUNNER_TEMP/html-reports
          xcrun xcresulttool \
            --format html \
            --output $RUNNER_TEMP/html-reports/test-results.html \
            --result-bundle $RUNNER_TEMP/test-results

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ runner.temp }}/test-results
          retention-days: 3

      - name: Upload HTML test reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-test-results
          path: ${{ runner.temp }}/html-reports/test-results.html
          retention-days: 3

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build archive
        run: |
          xcodebuild -scheme "IBHGithubAction" \
          -archivePath $RUNNER_TEMP/IBHGithubAction.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive

      - name: Export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/IBHGithubAction.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build

      - name: Verify if IPA file exists
        run: |
          if [ -f "$RUNNER_TEMP/build/IBHGithubAction.ipa" ]; then
            echo "IPA file exists"
          else
            echo "IPA file not found"
            exit 1
          fi

      - name: Upload application as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/IBHGithubAction.ipa
          retention-days: 3
